var tableauQuestion = [
    {   question : "Hvis du kører 80 kmh, og du nærmer dig et boligområde, betyder det",
        propositionA : "Du bliver nødt til at fremskynde fremad",
        propositionB : "Du kan fremskynde så længe der ikke er andre biler",
        propositionC : "Du bliver nødt til at bremse",
        propositionD : "Du kan bevare din hastighed",
        reponse : "C"},
		
    {   question : "Mens du drejer til venstre på et grønt lys, ser du, at en fodgænger er i krydset. Hvem har ret til vejen?",
        propositionA : "Fodgængeren, fordi de kan krydse vejen med ethvert lys",
        propositionB : "Dit køretøj, fordi lyset er grønt",
        propositionC : "Fodgængeren, fordi hun krydser med det grønne lys",
        propositionD : "Dit køretøj, fordi køretøjer altid gives retfærdigt",
        reponse : "C"},
		
    {   question : "Medmindre det er opgivet, er den maksimale hastighed i et boligområde ____ kmh.",
        propositionA : "50",
        propositionB : "55",
        propositionC : "65",
        propositionD : "70",
        reponse : "A"},
	
	{   question : "Før hver baneændring skal du.",
        propositionA : "Tjek dine spejle",
        propositionB : "Tjek dine blinde venkler",
        propositionC : "Signal dine hensigter",
        propositionD : "Alle de ovenstående",
        reponse : "D"},
		
	{   question : "Hvilket blodalkoholniveau er klassificeret som kørsel under beruset?",
        propositionA : "0.05%",
        propositionB : "0.18%",
        propositionC : "0.08%",
        propositionD : "0.06%",
        reponse : "C"},
		
	{   question : "Du skal trække og stoppe, indtil et nødkøretøj med en sirene er gået, medmindre:",
        propositionA : "Du har travlt",
        propositionB : "Der er plads til dem i en anden bane",
        propositionC : "Du er i en skolezone",
        propositionD : "Du er i et kryds",
        reponse : "D"},
	
	{   question : "Højer af vejen skal gives til nødkøretøjer",
        propositionA : "På alle tidspunkter",
        propositionB : "Blinkende røde, blå eller hvide lys",
        propositionC : "Brug af sirene eller blinkende røde, blå eller hvide lys",
        propositionD : "Brug en sirene",
        reponse : "C"},
		
	{   question : "Hvilket af følgende er tilladt, når du passerer et andet køretøj?",
        propositionA : "Følger nøje",
        propositionB : "Forlader den vigtigste rejste vejbane",
        propositionC : "Kørsel på den modsatte side af vejen",
        propositionD : "Overskrider hastighedsgrænsen",
        reponse : "C"},
		
	{   question : "Du kører på en motorvej med en anslået hastighedsgrænse på 110 kmh. Størstedelen af trafikken rejser på 120 km / t, så du skal køre ikke hurtigere end",
        propositionA : "80 kmh",
        propositionB : "40 kmh",
        propositionC : "50 kmh",
        propositionD : "110 kmh",
        reponse : "D"},
		
	{   question : "Når det bliver sendt af et andet køretøj, er det vigtigt ikke at",
        propositionA : "Sænk farten",
        propositionB : "Tjek dine spejle",
        propositionC : "Kig på den anden driver",
        propositionD : "Fremskynde",
        reponse : "D"},
]
